config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'homes#top'
  get 'home/about' => 'homes#about'

  get 'relationships/followers' => 'relationships#followers'

  resources :users, only: [:show, :index, :edit, :update] do
   resource :relationships, only: [:create, :destroy, :index]
   get 'followings' => 'relationships#followings', as: 'followings'
   get 'followers' => 'relationships#followers', as: 'followers'
 end
  resources :books, only: [:create, :index, :show, :destroy, :edit, :update] do
    resource :favorites, only: [:create, :destroy]

    resources :book_comments, only: [:create, :destroy]
  end
 end

app/models/about.rb
class About < ApplicationRecord
  def new
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :body, presence: true,
             length: {maximum: 200}
  belongs_to :user
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

end

app/models/book_comment.rb
class BookComment < ApplicationRecord
  belongs_to :user
  belongs_to :book
  validates :comment, presence: true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :book
end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :books, dependent: :destroy
  has_many :book_comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy
  has_many :followers, through: :reverse_of_relationships, source: :follower
  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :followings, through: :relationships, source: :followed
  validates :introduction ,length: { maximum: 50 }
  validates :name ,presence: true, uniqueness: true, length: { minimum: 2, maximum: 20 }
  attachment :profile_image

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end
  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end
  def following?(user)
    followings.include?(user)
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!,except: [:top, :about]
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(resource)
  end


  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:email])
  end

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  def create
    @book = Book.find(params[:book_id])
    @comment = current_user.book_comments.new(book_comment_params)
    @comment.book_id = @book.id
    @comment.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    BookComment.find_by(id: params[:id], book_id: params[:book_id]).destroy
    redirect_back(fallback_location: root_path)
  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
    @book = Book.new
    @user = current_user
  end

  def show
    @book = Book.find(params[:id])
    @user = @book.user
    @books = @user.books.page(params[:page]).reverse_order
    @new_book = Book.new
    @book_comment = BookComment.new
  end

  def edit
    @book = Book.find(params[:id])
    @user = @book.user
    if @user == current_user
     render "edit"
    else
     redirect_to books_path
    end
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      flash[:success] = "You have updated book successfully."
      redirect_to book_path(@book)
    else
      render :edit
    end
  end

  def create
     @book = Book.new(book_params)
     @book.user_id = current_user.id
    if @book.save
      flash[:notice] = "You have created book successfully."
      redirect_to book_path(@book)
    else
      @books = Book.all
      @user = current_user
      render :index
    end
  end

  def destroy
    book = Book.find(params[:id])
    book.destroy
    if
      flash[:success] = "Book was successfully destroyed."
      redirect_to books_path
    end
  end


  private
  def book_params
    params.require(:book).permit(:title, :body)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.new(book_id: book.id)
    favorite.save
    redirect_back(fallback_location: root_path)
  end

  def destroy
    book = Book.find(params[:book_id])
    favorite = current_user.favorites.find_by(book_id: book.id)
    favorite.destroy
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController
  def create
    current_user.follow(params[:user_id])
    redirect_to request.referer
  end

  def destroy
    current_user.unfollow(params[:user_id])
    redirect_to request.referer
  end
#————————フォロー・フォロワー一覧を表示する-————————————
  def followings
    user = User.find(params[:user_id])
    @users = user.followings.all
  end

  def followers
    user = User.find(params[:user_id])
    @users = user.followers.all
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user = current_user
    @users = User.all
    @book = Book.new
  end

  def show
    @user = User.find(params[:id])
    @books = @user.books.page(params[:page]).reverse_order
    @book = Book.new

  end

  def edit
    @user = User.find(params[:id])
    if @user == current_user
     render "edit"
    else
     redirect_to current_user
    end
  end

  def update
    @user = User.find(params[:id])
     if @user.update(user_params)
      @user.save
      flash[:notice] = "You have updated user successfully."
      redirect_to user_path(@user.id)
     else
      render("users/edit")
     end
  end

  private

  def user_params
    params.require(:user).permit(:name, :profile_image, :introduction)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/post_comments_helper.rb
module PostCommentsHelper
end

app/helpers/post_images_helper.rb
module PostImagesHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_list.html.erb
<% if book.errors.any? %>
    <%= book.errors.count %>error prohibited this obj from being saved:
  <% book.errors.full_messages.each do |message| %>
    <%= message %>
  <% end %>
<% end %>


<table class="table">
    <h1>User info</h1>
 <%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg" %>


 <tbody>
   <% if @user == current_user %>
 <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
    </tr>
    <tr>
      <th>フォロー数: </th>
      <th><%= link_to user_followings_path(user.id) do%>
          <%= user.followings.count %></th>
          <% end %>
    </tr>
    <tr>
      <th>フォロワー数: </th>
      <th>
        <%= link_to user_followers_path(user.id) do%>
          <%= user.followers.count %></th>
          <% end %>
    </tr>
      <th><%= user.introduction %></th>
    </tr>
      <th>
      <%= link_to  edit_user_path(user) do%>
       <i class="fas fa-user-cog"></i>
   </th>
   <% end %>
   <% else %>
   <tr>
      <th>name</th>
      <th><%= user.name %></th>
    </tr>
    <tr>
      <th>introduction</th>
    </tr>
    <tr>
      <th>フォロー数: </th>
      <th><%= link_to user_followings_path(user.id) do%>
          <%= user.followings.count %></th>
          <% end %>
    </tr>
    <tr>
      <th>フォロワー数: </th>
      <th>
        <%= link_to user_followers_path(user.id) do%>
          <%= user.followers.count %></th>
          <% end %>
    </tr>
      <th><%= user.introduction %></th>
    </tr>
    <tr>
      <th>
      <%= link_to  edit_user_path(user) do%>
       <i class="fas fa-user-cog"></i>
       </th></tr>
       <tr>
       <th>
       <td><%= render 'relationships/follow_button', user: user %></td>
       </th>
       </tr>
      <% end %>
      <% end %>
    </tbody>
 </tr>
</table>
<h2>New book</h2>
<!-- form_with部分 -->
<%= form_with model: book, url:'/books', local:true do |f| %>
  <p>Tilte</p>
  <%= f.text_field :title %>
  <p>Opinion</p>
  <%= f.text_area :body %>
  <p><%= f.submit 'Create Book' %></p>

<% end %>

app/views/books/edit.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">


    <div><h1>Editing Book</h1></div>
    <%= form_with model:@book, local: true do |f| %>
    <div id='error_explanation'>
    <% if @book.errors.any? %>
      <%= @book.errors.count %>error prohibited this book from being saved:<br>
      <% @book.errors.full_messages.each do |message| %>
        <%= message %><br>
     <% end %>
<% end %>
</div>
  <div><p>Title</p>
  <%= f.text_field :title %></div>
  <div><p>Opinion</p>
  <%= f.text_area :body %></div>
  <div><%= f.submit 'Update Book' %></div>

<% end %>

<%= link_to "Show", book_path(@book.id) %>
| <%= link_to "Back", books_path %>
  </div>
</div>
      </div>

app/views/books/index.html.erb
<p id="notice"></p>
<div class="container">
 <div class="row">
  <div class="col-md-3">
    <%= render 'books/list', user: @user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table">
      <thead>
      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      </tr>
      </thead>
    </div>
    <tbody>
    <% @books.each do |book| %>
     <div class="row">
      <tr>
      <td><%= link_to user_path(book.user_id) do %>
      <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'40x40' %></td>
      <% end %>
      <td><%= link_to book.title, book_path(book.id) %></td>
      <td><%= book.body %></td>
       <td> <% if book.favorited_by?(current_user) %>
       <p>
         <%= link_to book_favorites_path(book), method: :delete do %>
           ♥<%= book.favorites.count %> いいね
         <% end %>
       </p>
       <% else %>
       <p>
         <%= link_to book_favorites_path(book), method: :post do %>
           ♡<%= book.favorites.count %> いいね
         <% end %>
       </p></td>
       <% end %>
      <td><%= link_to "#{book.book_comments.count} コメント", book_path(book.id) %></td>
      </tr>
     </div>
    <% end %>
    </tbody>
    </table>
  </div>
 </div>
</div>

app/views/books/new.html.erb
<h1>Books#new</h1>
<p>Find me in app/views/books/new.html.erb</p>

app/views/books/show.html.erb
<div class="container">
 <div class="row">

   <div class="col-md-3">
     <%= render 'books/list', user: @user, book: @new_book %>
   </div>

   <div class="col-md-8 offset-md-1">
     <div class="row" />
       <h2>Book detail</h2>
       <table class="table">
        <thead>
         <th></th>
         <th></th>
         <th></th>
         <th></th>
         <th></th>
        </thead>
        <tbody>
         <tr>
      　   <td><%= link_to user_path(@user) do %>
      　   <%= attachment_image_tag @user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'40x40' %>
      　   <%= @user.name %>
      　   <% end %></td>
        　 <td><%= link_to @book.title, book_path(@book.id) %></td>
        　 <td><%= @book.body %></td>
       　   <td><%= attachment_image_tag @book, :image_id, :fill, 300, 300, format: 'jpeg' %></td>
       　   <td> <% if @book.favorited_by?(current_user) %>
             <p>
               <%= link_to book_favorites_path(@book), method: :delete do %>
                 ♥<%= @book.favorites.count %> いいね
               <% end %>
             </p>
           <% else %>
             <p>
               <%= link_to book_favorites_path(@book), method: :post do %>
                 ♡<%= @book.favorites.count %> いいね
               <% end %>
             </p></td>
           <% end %>
        　 <% if @book.user == current_user %>
        　<td><%= link_to "Edit", edit_book_path(@book.id) %></td>
        　<td><%= link_to "Destroy", book_path(@book), method: :delete %></td>
        　 <% end %>
      　  </tr>
        </tbody>
       </table>
     </div>
    　 <div class="comments">
         <p>コメント件数：<%= @book.book_comments.count %></p>
         <table>
           <tbody>
             <% @book.book_comments.each do |book_comment| %>
             <tr>
              <td>
                <%= link_to user_path(book_comment.user) do %>
                <%= attachment_image_tag book_comment.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'40x40' %>
                </td>
                <td><%= book_comment.user.name %></td>
                <% end %>
                <td><%= book_comment.comment %></td>
                <td>
                <% if book_comment.user == current_user %>
                 <%= link_to "削除", book_book_comment_path(book_comment.book, book_comment), method: :delete %>
                <% end %>
              </td>
             </tr>
             <% end %>
           </tbody>
         </table>
       </div>

       <div class="new-comment">
         <%= form_with(model:[@book, @book_comment], local: true) do |f| %>
           <%= f.text_area :comment, rows:'5',placeholder: "コメントをここに" %>
           <%= f.submit "送信する" %>
         <% end %>
       </div>
   </div>

 </div>
</div>

app/views/homes/about.html.erb
<body>
 <main>
  <p id="notice"></p>
  <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">Welcome to <i class="fas fa-book"></i><strong>Bookers</strong>!</h1>
   </div>
  </div>
 </main>
</body>

app/views/homes/top.html.erb
<body>
  <main>
        <p id="notice"></p>
        <div class="container">
  <div class="row">
    <div class="mx-auto col-11 col-sm-10 col-lg-8 col-xl-6">
      <h1>welcome to <i class="fas fa-book"></i><strong>Bookers</strong>  !!</h1>
      <p>In  <i class="fas fa-book"></i><strong>Bookers</strong>, </p>
      <p>you can share and exchange  your opinions , inpressions , and emotions</p>
      <p> about various books!</p>
      <div class="btn-wrapper col-10 mx-auto">
        <div class="row">
          <a class="btn btn-info btn-sm btn-block mb-3 sign_in" href="/users/sign_in">Log in</a>
        </div>
        <div class="row">
          <a class="btn btn-success btn-sm btn-block sign_up" href="/users/sign_up">Sign Up</a>
        </div>
      </div>
    </div>
  </div>
</div>


 </main>
</body>

app/views/relationships/_follow_button.html.erb
<% if user !=current_user %>
<% if current_user.following?(user) %>
  <%= link_to "Unfollow", user_relationships_path(user.id), method: :delete %>
<% else %>
  <%= link_to "Follow", user_relationships_path(user.id), method: :post %>
<% end %>
<% end %>

app/views/relationships/followers.html.erb
<h2>Follower Users</h2>
<% if @users.exists? %>
<div class="container">
 <div class="row">
   <div class="col-md-12">
  <table>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'40x40' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/relationships/followings.html.erb
<h2>Follow Users</h2>
<% if @users.exists? %>
<div class="container">
 <div class="row">
   <div class="col-md-12">
  <table>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'40x40' %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td><%= link_to "Show", user_path(user.id) %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
</div>
</div>
<% else %>
  <p>ユーザーはいません</p>
<% end %>

app/views/users/edit.html.erb
<main>
  <p id="notice"></p>
  <div class="container">
   <div class="row">
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
     <h2>User info</h2>
     <% if @user.errors.any? %>
     <%= @user.errors.count %>error prohibited this obj from being saved:<br>
     <% @user.errors.full_messages.each do |message| %>
     <%= message %>
     <% end %>
     <% end %>
     <%= form_with model:@user, local:true do |f| %>
     <label for="inputName">Name</label><br>
     <%= f.text_field :name, autofocus: true, placeholder:"名前"%><br>
     <label for="inputImage">Image</label><br>
     <%= f.attachment_field :profile_image, placeholder: "プロフィール画像" %><br>
     <label for="inputName">Introduction</label><br>
     <%= f.text_area :introduction %><br>
     <%= f.submit "Update User" %><br>
     <% end %>
    </div>
   </div>
  </div>
</main>

app/views/users/index.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
   <%= render 'books/list', user: @user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
   <h2>Users</h2>
   <table class="table">
    <thead>
     <tr>
      <th>image</th>
      <th>name</th>
      <th></th>
     </tr>
    </thead>
    <tbody>
    <% @users.each do |user| %>
     <div class="row">
      <tr>
       <td><%= attachment_image_tag user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'40x40' %></td>
       <td><%= user.name %></td>
       <td>フォロー数: <%= user.followings.count %></td>
       <td>フォロワー数: <%= user.followers.count %></td>
       <td><%= render 'relationships/follow_button', user: user %></td>
       <td><%= link_to "Show", user_path(user.id) %></td>
       <% end %>
      </tr>
     </div>
    </tbody>
    </table>
  </div>
 </div>
</div>

app/views/users/show.html.erb
<p id="notice"></p>
<div class="container px-5 px-sm-0">
 <div class="row">
  <div class="col-md-3">
    <%= render 'books/list', user: @user, book: @book %>
  </div>
  <div class="col-md-8 offset-md-1">
    <h2>Books</h2>
    <table class="table">
      <thead>
      <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      </tr>
      </thead>
     <tbody>
      <% @books.each do |book| %>
      <div class="row">
       <tr>
        <td><%= link_to user_path(book.user_id) do %>
        <%= attachment_image_tag book.user, :profile_image, :fill, 60, 60, fallback: "no_image.jpg", size:'40x40' %></td>
        <% end %>
        <td><%= link_to book.title, book_path(book.id) %></td>
        <td><%= book.body %></td>
        <% end %>
       </tr>
      </div>
     </tbody>
    </table>
  </div>
 </div>
</div>